#!/usr/bin/env bash
# Interactive configuration wizard
# Writes ~/.dev-setup-config with user preferences

source "$(dirname "$0")/colors.sh"

CONFIG_FILE="$HOME/.dev-setup-config"

prompt_with_default() {
  local question="$1"
  local default="$2"
  local var_name="$3"

  if [[ -n "$default" ]]; then
    echo -ne "  ${CYAN}?${NC}  ${question} ${DIM}[${default}]${NC}: "
  else
    echo -ne "  ${CYAN}?${NC}  ${question}: "
  fi

  read -r input
  input="${input:-$default}"
  eval "$var_name='$input'"
}

prompt_choice() {
  local question="$1"
  local options="$2"   # e.g. "windsurf|cursor|vscode"
  local default="$3"
  local var_name="$4"

  echo -e "  ${CYAN}?${NC}  ${question}"
  IFS='|' read -ra opts <<< "$options"
  local i=1
  for opt in "${opts[@]}"; do
    if [[ "$opt" == "$default" ]]; then
      echo -e "      ${BOLD}${i}) ${opt}${NC} ${DIM}(default)${NC}"
    else
      echo -e "      ${i}) ${opt}"
    fi
    ((i++))
  done
  echo -ne "  ${DIM}Enter number${NC}: "
  read -r choice

  # Default to first option if empty
  choice="${choice:-1}"
  local selected="${opts[$((choice-1))]}"
  selected="${selected:-$default}"
  eval "$var_name='$selected'"
}

prompt_yn() {
  local question="$1"
  local default="$2"   # "y" or "n"
  local var_name="$3"

  local hint="[Y/n]"
  [[ "$default" == "n" ]] && hint="[y/N]"

  echo -ne "  ${CYAN}?${NC}  ${question} ${DIM}${hint}${NC}: "
  read -r input
  input="${input:-$default}"
  input=$(echo "$input" | tr '[:upper:]' '[:lower:]')
  [[ "$input" == "y" || "$input" == "yes" ]] && eval "$var_name=true" || eval "$var_name=false"
}

run_configure() {
  step "Configuration"
  echo -e "  ${DIM}Press Enter to accept defaults. Config saved to ~/.dev-setup-config${NC}\n"

  # Git identity
  local git_name git_email
  git_name=$(git config --global user.name 2>/dev/null || echo "")
  git_email=$(git config --global user.email 2>/dev/null || echo "")
  prompt_with_default "Full name (for git commits)" "$git_name" "GIT_NAME"
  prompt_with_default "Email (for git commits)" "$git_email" "GIT_EMAIL"

  # GitHub username
  local gh_user
  gh_user=$(gh api user --jq '.login' 2>/dev/null || echo "")
  prompt_with_default "GitHub username" "$gh_user" "GITHUB_USER"

  # AI editor
  local detected="${DETECTED_EDITOR:-windsurf}"
  prompt_choice "Which AI editor do you use?" "windsurf|cursor|vscode|other" "$detected" "AI_EDITOR"

  # Jira
  local use_jira
  prompt_yn "Do you use Jira?" "y" "USE_JIRA"
  JIRA_WORKSPACE=""
  if [[ "$USE_JIRA" == "true" ]]; then
    prompt_with_default "Jira workspace URL" "yourteam.atlassian.net" "JIRA_WORKSPACE"
  fi

  # Branch naming
  step "Branch naming convention"
  echo -e "  ${DIM}Variables: {username}, {ticket}, {type}, {description}${NC}"
  echo -e "  ${DIM}Examples:${NC}"
  echo -e "  ${DIM}  {username}/{ticket}/{description}   →  fzacarias/FIRE-123/add-kafka-event${NC}"
  echo -e "  ${DIM}  feature/{ticket}-{description}      →  feature/FIRE-123-add-kafka-event${NC}"
  echo -e "  ${DIM}  {type}/{ticket}/{description}        →  feat/FIRE-123/add-kafka-event${NC}"
  prompt_with_default "Branch name pattern" "{username}/{ticket}/{description}" "BRANCH_PATTERN"

  # Conventional commits
  step "Conventional commits"
  local use_conventional
  prompt_yn "Enforce conventional commit format?" "y" "USE_CONVENTIONAL_COMMITS"

  COMMIT_TYPES="feat|fix|test|refactor|chore|docs|ci|perf|build|revert"
  if [[ "$USE_CONVENTIONAL_COMMITS" == "true" ]]; then
    prompt_with_default "Allowed commit types (pipe-separated)" "$COMMIT_TYPES" "COMMIT_TYPES"
    echo -e "  ${DIM}Format: type(scope): message  →  feat(auth): add OAuth2 support${NC}"
  fi

  # Claude commands
  local install_commands
  prompt_yn "Install Claude Code slash commands (~/.claude/commands/)?" "y" "INSTALL_COMMANDS"

  # Git hooks
  local install_hooks
  prompt_yn "Install git hooks globally (applies to all new repos)?" "n" "INSTALL_HOOKS_GLOBAL"

  # Write config
  step "Saving configuration"

  cat > "$CONFIG_FILE" << EOF
# Dev Setup Configuration
# Generated by ai-dev-setup on $(date +%Y-%m-%d)
# Edit manually or re-run: setup --configure

GIT_NAME="$GIT_NAME"
GIT_EMAIL="$GIT_EMAIL"
GITHUB_USER="$GITHUB_USER"
AI_EDITOR="$AI_EDITOR"
USE_JIRA="$USE_JIRA"
JIRA_WORKSPACE="$JIRA_WORKSPACE"
BRANCH_PATTERN="$BRANCH_PATTERN"
USE_CONVENTIONAL_COMMITS="$USE_CONVENTIONAL_COMMITS"
COMMIT_TYPES="$COMMIT_TYPES"
INSTALL_COMMANDS="$INSTALL_COMMANDS"
INSTALL_HOOKS_GLOBAL="$INSTALL_HOOKS_GLOBAL"
EOF

  ok "Config saved to $CONFIG_FILE"
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  run_configure
fi
